name: Release Starter Kit

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for this starter kit release (e.g. v1.0.0)"
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  package-and-upload:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v4

    - name: Package for macOS
      run: |
        mkdir -p dist/macos/xmlui-starter-kit
        cp -r app dist/macos/xmlui-starter-kit/
        cp install-mac.sh dist/macos/xmlui-starter-kit/
        tar -czf starter-kit-mac.tar.gz -C dist/macos xmlui-starter-kit

    - name: Package for Windows
      run: |
        mkdir -p dist/windows/xmlui-starter-kit
        cp -r app dist/windows/xmlui-starter-kit/
        cp install-windows.bat dist/windows/xmlui-starter-kit/
        cd dist/windows
        zip -r ../../starter-kit-windows.zip xmlui-starter-kit

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: |
          starter-kit-mac.tar.gz
          starter-kit-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
